server:
    port: ${PORT:5000}


spring:
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/changelog-master.xml
    jpa:
        hibernate:
            ddl-auto: create-drop