spring:
  datasource:
    url: jdbc:h2:./hexlet
    username: sa
    password: sa
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
  logging:
    level:
      root: INFO
      web: DEBUG